# Generated by Django 5.0.4 on 2024-05-04 14:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="MedicalAnalysis",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(max_length=200, verbose_name="Analysis Title"),
                ),
                (
                    "min_val",
                    models.CharField(
                        max_length=5, verbose_name="Analysis Minimum Value"
                    ),
                ),
                (
                    "curr_val",
                    models.CharField(
                        max_length=5, verbose_name="Analysis Current Value"
                    ),
                ),
                (
                    "max_val",
                    models.CharField(
                        max_length=5, verbose_name="Analysis Maximum Value"
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Medical Analysis",
            },
        ),
        migrations.CreateModel(
            name="MedicalAdvaices",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("advice", models.TextField(verbose_name="Medical Advice")),
                (
                    "analysis",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="medical_report.medicalanalysis",
                        verbose_name="Medical Analysis",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Medical Advaices",
            },
        ),
        migrations.CreateModel(
            name="Patient",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "full_name",
                    models.CharField(max_length=200, verbose_name="Patient Full Name"),
                ),
                (
                    "address",
                    models.CharField(max_length=200, verbose_name="Patient Address"),
                ),
                (
                    "image",
                    models.ImageField(
                        upload_to="Patient/Images/", verbose_name="Patient Image"
                    ),
                ),
                (
                    "phone",
                    models.CharField(
                        max_length=15, unique=True, verbose_name="Patient Phone"
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Patient User",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Patient",
            },
        ),
        migrations.AddField(
            model_name="medicalanalysis",
            name="patient",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="medical_report.patient",
                verbose_name="Analysis User",
            ),
        ),
    ]
